import sys; sys.path.insert(0, ".")
from common import *
games = select_games()
print("N games:", len(games)); print(games[0])
from collections import Counter; print(Counter(task_type(g) for g in games))
env = make_env(games[0]); obs, info = env.reset()
print(repr(obs[:600])); print(info["admissible_commands"][0][:8])
obs, r, done, info = env.step([info["admissible_commands"][0][0]])
print(obs[0][:200], r, done, info["won"])
txt, u = llm([{"role":"user","content":"Reply with exactly the word OK."}], tag="smoke", max_tokens=5)
print("LLM:", txt, u)
