[project]
name = "catan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catanatron",
    "openai>=3.19.2",
    "python-dotenv>=1.2.3",
]

[tool.uv.sources]
catanatron = { git = "https://github.com/bcollazo/catanatron" }
